version: '3.2'
services:
  node:
    container_name: node-watcher
    build: ./
    restart: always
    env_file: docker-compose.env
    networks:
      - my-bridge-network
    volumes:
      - ./src/data:/var/lib/app-data
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://${LOGSTASH_HOST}:${LOGSTASH_PORT}'
networks:
  my-bridge-network:
    external: true
