version: '3.3'
services:
  engaged_db:
    build: ./
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    expose:
      - '3306'
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf:ro